"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y)$2mrpn5k@+4r#k$mbmqt!c#o9kbq!ge%2-nuqr$vsx3-g0e4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework for API functionality
    'corsheaders',     # CORS headers middleware for cross-origin requests
    'upload',          # Custom app for handling file uploads to Azure Storage
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be placed high in middleware stack
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Allows cross-origin requests from the React frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server default port
]

# Azure Storage Configuration
# These settings are required for uploading files to Azure Blob Storage
# In production, these should be set via environment variables for security

# Azure Storage Account URL - the base URL for your storage account
# Format: https://<storage_account_name>.blob.core.windows.net
# AZURE_STORAGE_ACCOUNT_URL = ""

# # Azure Storage SAS Token - provides time-limited access to storage resources
# # Should include permissions for reading, writing, and creating blobs
# # Format: ?sv=2021-06-08&ss=b&srt=sco&sp=rwdlacupx&se=...
# AZURE_STORAGE_SAS_TOKEN = ""

# # Azure Container Name - the blob container where files will be stored
# # Container must exist in the storage account before uploading
# AZURE_CONTAINER_NAME = ""

AZURE_STORAGE_ACCOUNT_URL = "https://pmrsstorage.blob.core.windows.net"
AZURE_STORAGE_SAS_TOKEN = "sp=rw&st=2025-07-31T10:28:29Z&se=2025-08-01T15:30:29Z&spr=https&sv=2024-11-04&sr=c&sig=jf8ViOPSl%2FIEN87sJAk%2FIOy4%2B%2F41LW1CGcSpbMBwUmc%3D"
AZURE_CONTAINER_NAME = "large-file-upload"

# Chunk Size Configuration
# Defines the size of each chunk for large file uploads (10MB)
# This should match the CHUNK_SIZE constant in the frontend
# Larger chunks = fewer HTTP requests but more memory usage
# Smaller chunks = more HTTP requests but better progress granularity
CHUNK_SIZE = 10 * 1024 * 1024 # 10 MB
